[package]
publish = false
name = "regex-automata-examples"
version = "0.0.0"  #:version
edition = "2018"

[dev-dependencies]
fst = "0.4.0"
regex-automata = { version = "*", path = "..", features = ["transducer"] }

[[example]]
name = "fst"
path = "fst.rs"
