# Source: http://lh3lh3.users.sourceforge.net/reb.shtml

# Haystack is: lh3lh3-reb-howto.txt

# ([a-zA-Z][a-zA-Z0-9]*)://([^ /]+)(/[^ ]*)?
# ([^ @]+)@([^ @]+)
# ([0-9][0-9]?)/([0-9][0-9]?)/([0-9][0-9]([0-9][0-9])?)
# ([a-zA-Z][a-zA-Z0-9]*)://([^ /]+)(/[^ ]*)?|([^ @]+)@([^ @]+)
