# Source: https://github.com/mariomka/regex-benchmark

# Haystack is: mariomka-input-text.txt

# [\w\.+-]+@[\w\.-]+\.[\w\.-]+
# [\w]+://[^/\s?#]+[^\s?#]+(?:\?[^\s#]*)?(?:#[^\s]*)?
# (?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9])
