[[benches]]
type = "regex-redux"
name = "fasta-100000"
regex = ''
haystack-path = "regex-redux.txt"
case-insensitive = false
unicode = false
engines = [
  'regex/api',
  'regex/automata/dense',
  'regex/automata/hybrid',
  'regex/automata/pikevm',
  're2/api',
  'pcre2/api/jit',
  'pcre2/api/nojit',
]
analysis = 'TODO'
