[[benches]]
type = "count"
name = "literal-en"
regex = 'Sherlock Holmes'
haystack-path = "opensubtitles/en-huge.txt"
case-insensitive = false
unicode = false
match-count = 1
engines = [
  'regex/api',
  'memchr/memmem',
  'regexold/api',
  're2/api',
  'pcre2/api/jit',
  'pcre2/api/nojit',
]
analysis = 'TODO'

[[benches]]
type = "count"
name = "literal-ru"
regex = 'Шерлок Холмс'
haystack-path = "opensubtitles/ru-huge.txt"
case-insensitive = false
unicode = true
match-count = 1
engines = [
  'regex/api',
  'memchr/memmem',
  'regexold/api',
  're2/api',
  'pcre2/api/jit',
  'pcre2/api/nojit',
]
analysis = 'TODO'

[[benches]]
type = "count"
name = "literal-en-casei"
regex = 'sherlock holmes'
haystack-path = "opensubtitles/en-huge.txt"
case-insensitive = true
unicode = false
match-count = 1
engines = [
  'regex/api',
  'regexold/api',
  're2/api',
  'pcre2/api/jit',
  'pcre2/api/nojit',
]
analysis = 'TODO'

[[benches]]
type = "count"
name = "literal-ru-casei"
regex = 'шерлок холмс'
haystack-path = "opensubtitles/ru-huge.txt"
case-insensitive = true
unicode = true
match-count = 1
engines = [
  'regex/api',
  'regexold/api',
  're2/api',
  'pcre2/api/jit',
  'pcre2/api/nojit',
]
analysis = 'TODO'
