# Source: https://zherczeg.github.io/sljit/regex_perf.html
# Source: https://github.com/rust-leipzig/regex-performance

# Haystack is: zherczeg-mtent12.txt

# Twain
# (?i)Twain
# [a-z]shing
# Huck[a-zA-Z]+|Saw[a-zA-Z]+
# \b\w+nn\b
# [a-q][^u-z]{13}x
# Tom|Sawyer|Huckleberry|Finn
# (?i)Tom|Sawyer|Huckleberry|Finn
# .{0,2}(Tom|Sawyer|Huckleberry|Finn)
# .{2,4}(Tom|Sawyer|Huckleberry|Finn)
# Tom.{10,25}river|river.{10,25}Tom
# [a-zA-Z]+ing
# \s[a-zA-Z]{0,12}ing\s
# ([A-Za-z]awyer|[A-Za-z]inn)\s
# ["'][^"']{0,30}[?!\.]["']
# ∞|✓
# \p{Sm}
# (.*?,){13}z
